# Site settings
title: Arnaud Nauwynck's github.io site
email: arnaud.nauwynck@gmail.com
description: >
  My personal github.io web site: blog, articles, ...
baseurl: ""

# TEMPOARY before asset/ images are uploaded
# url: "http://localhost:4000"
url: "http://arnaud-nauwynck.github.io"


github_username:  Arnaud-Nauwynck


# Build settings
markdown: kramdown

highlighter: pygments

